const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)];
const head=$("header"),nav=$("nav"),menu=$(".menu"),backdrop=$(".nav-backdrop"),navClose=$(".nav-close");
addEventListener("scroll",()=>head.classList.toggle("stick",scrollY>20),{passive:true});
function setMenu(open){nav.classList.toggle('open',open);backdrop.classList.toggle('open',open);backdrop.setAttribute('aria-hidden',String(!open));menu.setAttribute('aria-expanded',String(open));document.body.classList.toggle('menu-open',open);menu.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú');if(open){requestAnimationFrame(()=>navClose.focus())}}
menu.onclick=()=>setMenu(!nav.classList.contains('open'));addEventListener('resize',()=>{if(innerWidth>=1050&&nav.classList.contains('open'))setMenu(false)},{passive:true});navClose.onclick=()=>setMenu(false);backdrop.onclick=()=>setMenu(false);$$('nav a').forEach(a=>a.onclick=()=>setMenu(false));addEventListener('keydown',e=>{if(e.key==='Escape')setMenu(false)});
let i=0,t;const slides=$$('.slide'),dots=$$('.dots button');
function show(n){i=(n+slides.length)%slides.length;slides.forEach((s,x)=>s.classList.toggle('active',x===i));dots.forEach((d,x)=>d.classList.toggle('on',x===i));clearInterval(t);t=setInterval(()=>show(i+1),2500)}
dots.forEach((d,x)=>d.onclick=()=>show(x));show(0);
const revealObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');revealObserver.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(e=>revealObserver.observe(e));
const portalButtons=$$('.chips button'),portalScreens=$$('.portal-screen'),progress=$('.portal-progress i');let portalIndex=0,portalTimer;
function setPortal(index,user=false){portalIndex=(index+portalButtons.length)%portalButtons.length;portalButtons.forEach((b,x)=>{const active=x===portalIndex;b.classList.toggle('active',active);b.setAttribute('aria-selected',active)});portalScreens.forEach((s,x)=>s.classList.toggle('active',x===portalIndex));progress.style.transform=`translateX(${portalIndex*100}%)`;if(user)startPortal()}
function startPortal(){clearInterval(portalTimer);portalTimer=setInterval(()=>setPortal(portalIndex+1),2400)}
portalButtons.forEach((b,x)=>b.addEventListener('click',()=>setPortal(x,true)));
const portalObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){startPortal();portalObserver.unobserve(e.target)}}),{threshold:.25});portalObserver.observe($('#portal'));setPortal(0);
const stableObserver=new IntersectionObserver(es=>es.forEach(e=>{e.target.classList.toggle('in-view',e.isIntersecting)}),{threshold:.38,rootMargin:'-8% 0px -12%'});$$('.gallery-card,.cards article,.feature img,.btn,.pill,.wa').forEach(el=>stableObserver.observe(el));
$$('.gallery-card').forEach(card=>{card.addEventListener('touchstart',()=>card.classList.add('touch-tilt'),{passive:true});card.addEventListener('touchend',()=>setTimeout(()=>card.classList.remove('touch-tilt'),420),{passive:true})});
let pulseIndex=0;const pulseTargets=$$('.btn,.pill,.wa');setInterval(()=>{pulseTargets.forEach(x=>x.classList.remove('soft-pulse'));if(document.visibilityState==='visible'&&pulseTargets.length){pulseTargets[pulseIndex%pulseTargets.length].classList.add('soft-pulse');pulseIndex++}},3200);
const form=$('#form');
function validate(input){const error=input.parentElement.querySelector('.error');let msg='';const val=input.value.trim();if(!val)msg='Este campo es obligatorio.';else if(input.name==='n'&&val.length<2)msg='Escribe al menos 2 caracteres.';else if(input.name==='t'&&!/^\d{10}$/.test(val.replace(/\D/g,'')))msg='Ingresa un número de 10 dígitos.';else if(input.name==='z'&&val.length<3)msg='Escribe una colonia o municipio válido.';else if(input.name==='m'&&val.length<10)msg='Describe el caso con al menos 10 caracteres.';input.classList.toggle('invalid',!!msg);error.textContent=msg;return !msg}
$$('input,select,textarea',form).forEach(input=>{input.addEventListener('blur',()=>validate(input));input.addEventListener('input',()=>{if(input.name==='t')input.value=input.value.replace(/\D/g,'').slice(0,10);if(input.classList.contains('invalid'))validate(input)})});
form.onsubmit=e=>{e.preventDefault();const fields=$$('input,select,textarea',form),ok=fields.map(validate).every(Boolean);if(!ok){$('.invalid',form)?.focus();form.classList.add('form-shake');setTimeout(()=>form.classList.remove('form-shake'),400);return}form.classList.add('success');setTimeout(()=>form.classList.remove('success'),900);const d=new FormData(form),phone=d.get('t').replace(/\D/g,''),text=`Hola Fumi-Car, soy ${d.get('n')}.\nMi teléfono: ${phone}\nEspacio: ${d.get('e')}\nZona: ${d.get('z')}\nMensaje: ${d.get('m')}`;open('https://wa.me/525547117493?text='+encodeURIComponent(text),'_blank','noopener')};
const lb=$('.lightbox');$$('.gallery button').forEach(b=>b.onclick=()=>{lb.hidden=false;$('img',lb).src=b.dataset.src;document.body.style.overflow='hidden'});$('.lightbox button').onclick=()=>{lb.hidden=true;document.body.style.overflow=''};lb.onclick=e=>{if(e.target===lb)$('.lightbox button').click()};
$('#year').textContent=new Date().getFullYear();